## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main, pipeline-develop ]
  pull_request:
    branches: [ main ]

env:
  REGION: europe-central2

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Write private key
        run: |
          mkdir META-INF
          echo "${JWT_PUBLIC_KEY}" > META-INF/publicKey.pem
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build
        run: mvn -B -DskipTests clean package
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GCR
        id: docker-auth
        uses: 'docker/login-action@v3'
        with:
          registry: 'gcr.io'
          username: '_json_key'
          password: '${{ secrets.GCP_CLOUD_RUNNER_CREDENTIALS }}'
      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            gcr.io/stock-echoes-gcp/stock-echoes-server:latest
